language: c

dist: xenial

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - MAKETARGET="test-all tidy-all check-format"
      addons:
        apt:
          packages:
            - valgrind
            - python3
            - python3-setuptools
            - python3-pip
    - os: linux
      compiler: clang
      env:
        - MAKETARGET=test-all
      addons:
        apt:
          packages:
            - valgrind
            - python3
            - python3-setuptools
            - python3-pip
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env:
        - MAKETARGET=test-all
    - os: osx
      osx_image: xcode10.1
      compiler: gcc
      addons:
        homebrew:
          packages:
            - gcc@8
      env:
        - MAKETARGET=test-all

before_install:
  - python3 --version
  - pip3 install -r requirements.txt

script:
  - make ${MAKETARGET}


cache: pip

#  vim: set ft=yaml ts=2 sw=2 tw=0 et :
