language: c

dist: xenial

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - MAKETARGET="test-all tidy-all check-format"
    - os: linux
      compiler: clang
      env:
        - MAKETARGET=test-all
    - os: osx
      compiler: clang
      env:
        - MAKETARGET=test-all
    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="brew upgrade && brew install gcc && CC=gcc-8 && CXX=g++-8"
        - MAKETARGET=test-all

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make ${MAKETARGET}


#  vim: set ft=yaml ts=2 sw=2 tw=0 et :
