language: c

dist: xenial

matrix:
  include:
    - name: "MacOS + Clang"
      os: osx
      osx_image: xcode10.1
      compiler: clang
      before_install:
        - pip3 install -r requirements.txt
      env:
        - MAKETARGET=test-all
    - name: "MacOS + GCC8"
      os: osx
      osx_image: xcode10.1
      compiler: gcc
      addons:
        homebrew:
          packages:
            - gcc@8
      before_install:
        - pip3 install -r requirements.txt
        - gcc --version
      env:
        - MAKETARGET=test-all

env:
  matrix:
    - CC=gcc    ARCH=armhf
    - CC=clang  ARCH=armhf
    - CC=gcc    ARCH=arm64
    - CC=clang  ARCH=arm64
    - CC=gcc    ARCH=i386
    - CC=clang  ARCH=i386
    - CC=gcc    ARCH=amd64
    - CC=clang  ARCH=amd64
    - CC=gcc    ARCH=unstable-ppc
    - CC=clang  ARCH=unstable-ppc

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - docker run --rm -v `pwd`:`pwd` -w `pwd` "pqclean/ci-containers:$ARCH" /bin/bash -c "
      uname -a &&
      export CC=${CC} &&
      cd test && python3 -m nose --rednose --verbose"

cache: pip

#  vim: set ft=yaml ts=2 sw=2 tw=0 et :
