version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: minimal

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - scripts_windows\build_all.bat
